/**
 * <a href="http://www.openolat.org">
 * OpenOLAT - Online Learning and Training</a><br>
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); <br>
 * you may not use this file except in compliance with the License.<br>
 * You may obtain a copy of the License at the
 * <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache homepage</a>
 * <p>
 * Unless required by applicable law or agreed to in writing,<br>
 * software distributed under the License is distributed on an "AS IS" BASIS, <br>
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. <br>
 * See the License for the specific language governing permissions and <br>
 * limitations under the License.
 * <p>
 * Initial code contributed and copyrighted by<br>
 * frentix GmbH, http://www.frentix.com
 * <p>
 */
package org.olat.modules.video;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;

import org.olat.core.commons.services.image.Size;
import org.olat.core.util.vfs.VFSContainer;
import org.olat.core.util.vfs.VFSLeaf;
import org.olat.fileresource.types.ResourceEvaluation;
import org.olat.modules.video.manager.VideoExportMediaResource;
import org.olat.modules.video.model.VideoQualityVersion;
import org.olat.repository.RepositoryEntry;
import org.olat.resource.OLATResource;

/**
 * The <code>VideoManager</code> singleton is responsible for dealing with video
 * resources.
 *
 * Initial date: 01.04.2015<br>
 * @author Dirk Furrer, dirk.furrer@frentix.com, http://www.frentix.com
 */
public interface VideoManager {

	public abstract File getVideoFile(OLATResource video);

	public abstract Size getVideoSize(OLATResource video);

	public abstract void setVideoSize(OLATResource video, Size size);

	public abstract VFSLeaf getPosterframe(OLATResource video);

	public abstract void setPosterframe(OLATResource video, VFSLeaf posterframe);

	public abstract void setTitle(OLATResource video, String title);

	public abstract String getTitle(OLATResource video);

	public abstract HashMap<String, VFSLeaf> getAllTracks(OLATResource video);

	public abstract void addTrack(OLATResource video, String lang, VFSLeaf trackFile);

	public abstract VFSLeaf getTrack(OLATResource video, String lang);

	public abstract void removeTrack(OLATResource video, String lang);

	public abstract boolean getFrame(OLATResource video, int frameNumber, VFSLeaf frame) throws IOException;

	public abstract void setDescription(OLATResource video, String text);

	public abstract String getDescription(OLATResource video);

	/**
	 * Trigger the transcoding process to generate versions of the video
	 * 
	 * @param video
	 * @return
	 */
	public abstract void startTranscodingProcess(OLATResource video);
	
	public abstract List<VideoQualityVersion> getQualityVersions(OLATResource video);

	/**
	 * Get a human readable aspect ratio from the given video size. Recognizes
	 * the most common aspect ratios
	 * 
	 * @param videoSize
	 *            Must not be NULL
	 * @return String containing a displayable aspect ratio
	 */
	public abstract String getAspectRatio(Size videoSize);

	/**
	 * Get the media container for this resource where the actual video is stored
	 * @param videoResource
	 * @return VFSContainer
	 */
	public abstract VFSContainer getMediaContainer(OLATResource videoResource);
	
	/**
	 * Get the container where all the transcoded videos are stored
	 * @param videoResource
	 * @return VFSContainer
	 */
	public abstract VFSContainer getTranscodingContainer(OLATResource videoResource);
	
	/**
	 * Get the master video file 
	 * @param videoResource
	 * @return VFSLeaf or NULL if it does not exist
	 */
	public abstract VFSLeaf getMasterVideoFile(OLATResource videoResource);
	
	/**
	 * Get a media resource which represents an export of a video resource
	 * @param videoResource
	 * @return VideoExportMediaResource which generates a ZIP file on the fly
	 */
	public abstract VideoExportMediaResource getVideoExportMediaResource(OLATResource videoResource);

	/**
	 * Check if the given file is an archive generated by the export (and thus
	 * can be imported again). The validation callback is set to true if valid
	 * and the title and description are extracted
	 * 
	 * @param file
	 *            The zip file handle
	 * @param eva
	 *            the resource validation callback
	 * @return true: recognized as video resource; false: not recognized
	 */
	public abstract void validateVideoExportArchive(File file,  ResourceEvaluation eval);

	/**
	 * Import the given file to the resource on disk
	 * @param repoEntry 
	 *            The repository entry that represents the video in the repository
	 * @param masterVideo The video file to be added to the repository. Must be an mp4 file.
	 */
	public abstract boolean importFromMasterFile(RepositoryEntry repoEntry, VFSLeaf masterVideo);

	/**
	 * Import the given export archive to the resource on disk
	 * 
	 * @param repoEntry
	 *            The repository entry that represents the video in the repository
	 * @param exportArchive
	 *            The archive to be added to the repository. The archive must be
	 *            created by the video export feature.
	 */
	public abstract boolean importFromExportArchive(RepositoryEntry repoEntry, VFSLeaf exportArchive);

	/**
	 * Create and add a new transcoding version to the video resource. The
	 * version is set to "isTransforming".
	 * 
	 * @param video
	 *            The video resource
	 * @param resolution
	 *            The resolution for the transcoding process. This is the height
	 *            of the target video size (e.g. 720 for 720p resolution)
	 * @return VideoQualityVersion for this new version
	 */
	public abstract VideoQualityVersion addNewVersionForTranscoding(OLATResource video, int resolution);

	/**
	 * Update an already existing version or add as new version.
	 * 
	 * @param video
	 * @param updatedVersion
	 */
	public abstract void updateVersion(OLATResource video, VideoQualityVersion updatedVersion);

}