/**
 * <a href="https://www.openolat.org">
 * OpenOlat - Online Learning and Training</a><br>
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); <br>
 * you may not use this file except in compliance with the License.<br>
 * You may obtain a copy of the License at the
 * <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache homepage</a>
 * <p>
 * Unless required by applicable law or agreed to in writing,<br>
 * software distributed under the License is distributed on an "AS IS" BASIS, <br>
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. <br>
 * See the License for the specific language governing permissions and <br>
 * limitations under the License.
 * <p>
 * Initial code contributed and copyrighted by<br>
 * frentix GmbH, https://www.frentix.com
 * <p>
 */
package org.olat.core.commons.services.ai.essay;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.time.Instant;

import org.apache.logging.log4j.Logger;
import org.olat.core.logging.Tracing;
import org.springframework.stereotype.Service;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

/**
 *
 * On-disk store for the {@link AiSourceCompanion} POJO. The file is named
 * {@code ai-source.json} and lives in the same directory as the QTI item XML
 * it tags with AI provenance. Mirrors {@link EssayAiGradingFileStore}'s
 * write/read behaviour but for the much smaller MC / "source-only" payload.
 *
 * Initial date: 2026-04-20<br>
 *
 * @author Florian Gnägi, gnaegi, https://www.frentix.com
 *
 */
@Service
public class AiSourceCompanionFileStore {

	private static final Logger log = Tracing.createLoggerFor(AiSourceCompanionFileStore.class);

	/** Canonical filename written next to the QTI item XML. */
	public static final String FILENAME = "ai-source.json";

	private static final ObjectMapper MAPPER = createMapper();

	/**
	 * Load the companion POJO from {@code ai-source.json} inside the given
	 * question directory. Returns {@code null} when the file does not exist
	 * (item was not generated by AI, or the companion is missing).
	 */
	public AiSourceCompanion load(File questionDir) {
		if (questionDir == null) {
			return null;
		}
		File file = new File(questionDir, FILENAME);
		if (!file.exists() || !file.isFile()) {
			return null;
		}
		try {
			byte[] bytes = Files.readAllBytes(file.toPath());
			return MAPPER.readValue(bytes, AiSourceCompanion.class);
		} catch (IOException e) {
			log.warn("Failed to read {} from {}: {}", FILENAME, questionDir, e.getMessage());
			return null;
		}
	}

	/**
	 * Persist the companion POJO to {@code ai-source.json} inside the given
	 * question directory. Stamps {@code generatedAt} (ISO-8601 instant) when
	 * missing so the on-disk file always carries a timestamp.
	 */
	public void save(File questionDir, AiSourceCompanion companion) {
		if (questionDir == null || companion == null) {
			return;
		}
		if (!questionDir.exists() && !questionDir.mkdirs()) {
			log.warn("Cannot create question directory {}", questionDir);
			return;
		}
		if (companion.getGeneratedAt() == null || companion.getGeneratedAt().isBlank()) {
			companion.setGeneratedAt(Instant.now().toString());
		}
		try {
			byte[] bytes = MAPPER.writerWithDefaultPrettyPrinter().writeValueAsBytes(companion);
			File file = new File(questionDir, FILENAME);
			Files.write(file.toPath(), bytes);
		} catch (IOException e) {
			log.warn("Failed to write {} to {}: {}", FILENAME, questionDir, e.getMessage());
		}
	}

	/** Whether the store has a persisted file for the given question dir. */
	public boolean exists(File questionDir) {
		return questionDir != null && new File(questionDir, FILENAME).isFile();
	}

	/** Direct file accessor used by callers that need to byte-copy the on-disk file. */
	public File fileFor(File questionDir) {
		return questionDir == null ? null : new File(questionDir, FILENAME);
	}

	private static ObjectMapper createMapper() {
		ObjectMapper m = new ObjectMapper();
		m.configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);
		m.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
		m.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		return m;
	}
}
