/**
 * <a href="https://www.openolat.org">
 * OpenOlat - Online Learning and Training</a><br>
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); <br>
 * you may not use this file except in compliance with the License.<br>
 * You may obtain a copy of the License at the
 * <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache homepage</a>
 * <p>
 * Unless required by applicable law or agreed to in writing,<br>
 * software distributed under the License is distributed on an "AS IS" BASIS, <br>
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. <br>
 * See the License for the specific language governing permissions and <br>
 * limitations under the License.
 * <p>
 * Initial code contributed and copyrighted by<br>
 * frentix GmbH, https://www.frentix.com
 * <p>
 */
package org.olat.core.commons.services.ai.ui;

import java.util.Locale;

import org.olat.core.commons.services.ai.AiImageDescriptionService;
import org.olat.core.commons.services.ai.AiMCQuestionService;
import org.olat.core.commons.services.ai.model.AiImageDescriptionResponse;
import org.olat.core.commons.services.ai.model.AiMCQuestionsResponse;
import org.olat.core.commons.services.ai.model.ImageDescriptionData;
import org.olat.core.commons.services.ai.model.MCQuestionData;
import org.olat.core.gui.UserRequest;
import org.olat.core.gui.components.Component;
import org.olat.core.gui.components.velocity.VelocityContainer;
import org.olat.core.gui.control.Controller;
import org.olat.core.gui.control.Event;
import org.olat.core.gui.control.WindowControl;
import org.olat.core.gui.control.controller.BasicController;
import org.olat.core.gui.control.generic.closablewrapper.CloseableModalController;

/**
 * Controller that runs AI feature tests and displays results in a modal dialog.
 * Supports MC question generation and image description generation tests.
 *
 * Initial date: 20.03.2026<br>
 *
 * @author gnaegi@frentix.com, https://www.frentix.com
 *
 */
public class AiFeaturesTestController extends BasicController {

	// Test input: a paragraph about OpenOlat for MC question generation testing
	static final String MC_TEST_INPUT = "OpenOlat is a web-based learning management system (LMS) "
			+ "used for e-learning, teaching, and training. It supports course creation, "
			+ "assessments, forums, wikis, group management, and portfolio features. "
			+ "OpenOlat is open source software licensed under the Apache 2.0 license "
			+ "and developed by frentix GmbH in Zurich, Switzerland. It is widely used "
			+ "by universities, schools, and corporations for online and blended learning scenarios.";

	// Test input: a scaled-down (200px) base64-encoded JPEG of a cat with infinity symbol in cornfield at sunset
	static final String IMG_TEST_BASE64 = "/9j/4Q/+RXhpZgAATU0AKgAAAAgABgESAAMAAAABAAEAAAEaAAUAAAABAAAAVgEbAAUAAAABAAAAXgEoAAMAAAABAAIAAAITAAMAAAABAAEAAIdpAAQAAAAB"
			+ "AAAAZgAAAAAAAABIAAAAAQAAAEgAAAABAAeQAAAHAAAABDAyMjGRAQAHAAAABAECAwCgAAAHAAAABDAxMDCgAQADAAAAAQABAACgAgAEAAAAAQAABgCgAwAE"
			+ "AAAAAQAABACkBgADAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
			+ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9sAhAAQEBAQEBAcEBAcJxwcHCc1JycnJzVDNTU1NTVDUUNDQ0NDQ1FR"
			+ "UVFRUVFRYWFhYWFhcXFxcXF/f39/f39/f39/ARQVFSAeIDceHjeFWkpahYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWF"
			+ "hYX/3QAEABv/wAARCAEYAaQDASIAAhEBAxEB/8QBogAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoLEAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYT"
			+ "UWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaX"
			+ "mJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+foBAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKCxEA"
			+ "AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpj"
			+ "ZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oA"
			+ "DAMBAAIRAxEAPwDo6zdTl22UgHBI2D6ngVZDEjAPFc/cM7QKrHGx9jfQHiuS518pvwuiRBc/dAHHT6VFp774d7dWZm/DPH6VnXMhhtjngkYC+mOlT26NGiRD"
			+ "+EUrj5TbHNJxVPL+tNx+lPmFyl4sB1rNmnWRIsdHcH8BzVa+LCDdGeeB+fFV2QrcIP4UHA9+gpXGonQKQVzmkLACqyD5adtouHKOLsegpu6QUuO1JtNFwsIH"
			+ "enh2pu00m00rjsWAx9af5oHUVU2mlC0rhYurMvTFNKhvu1V2elSqjetK4WHbJh0NJtbPz08eYKl5b7woArvACMoKhEPatREp7KB0o5SefoZH2Z+wppt3XqK2"
			+ "MSY4puGPFHKPnMoQN0xQ8G0VrGMkc1WeMCk1YalczttKBV0qo6Uzy6ksrilxVgR0vl0gK22lxVsRCn/Zz2p2FzIoYo21e+zsKX7OxosxcyKQWn+We9XBbsKf"
			+ "5I9afKxc6M7GKaQTWiYEx1pqwr3NOzDmRSVDUwgyKteUoqQAAcCmoic+xUFqaa0G3irecUFh7U7C5mUPLxSbe1XcpWdcXaw3cKEYBJH4YpFXEu0ItZD/ALNT"
			+ "oucD1FRXs37h+OCpH+FV4rkiRF7+WP1oH0NcQrimMpxgUhnClVbjNRt855/D0p6dCVciXa4MD4DdMf4VjRBv9e2P9aS30HA/WtJx87uvBTBx26Vn2sn2m13P"
			+ "8rKwA/OkUjWjtyV3Nw59O1UJ7tQPLlBGD/Krk0r/AGbavBPCgetZt9brvSWE5+U5H4Uhoy7poUKbZNuUBx9aq+bH/wA9h+VNlkXIGeAoA6VFvX1/lVJBdH//"
			+ "0NE5WL7QmBgcgd//ANVZm8FhcKMoXZz7YGKme+UeZDJ+7ki3YU98iqrxFYo7ccqMsx/LivPO8ljPmfO/IYKR+PFaCMfOk8v5ug9hVGURR3EanOw4xjjNWvMl"
			+ "efykGxMAHA6/T0pXGTwMFt98nJJP86dbj5pm/wBv+gqtaxK6bGOdpGfz6VPbnbFLITglmx7UXCxVviJWjgTqzD9OaIgJblmA+7ioYyUii3ffBNX7CBwGfdkH"
			+ "Bz+GKLhsSzNsjJHJFWeN232zUTwymFgpBz26U8EpvkPXAAFFxD9tNf5ELEdKtLE+0Z61Xu1KQMB9KYk0AWnhKWMFxQ4YMqDq38hQFxdi08Inal8tqPKagm4u"
			+ "xKd5aU0RNTxF70/kK44RgVL8oFMAI707A71aM2OyKTIo+Wk4qhDg2KXcPSmcUUBYfuHpTCEbqKWigQwQx04RxCnUuKVl2Hdi4jHQUmI/7tGKXFUSGU9KNqHp"
			+ "xRikxQAmxfWlCqO9GKbikMXalOCpUdITjFA7EpTjAqsA3mtH2ABqTOKpbsXg90x+VTKw4otbH9KZtZ+nbipS2BVKCTHmlecP0/AVLSKVyO6VlVSvUMP8KsGI"
			+ "gc1Svn3RrInQMPyqeJ/MnK9Aiio6mmthYlL7mPGDjFY+oDMkUpGQn9eK1w+ySQkcZ/pWHqfPyqcBhjb6+mKBou3CvbxqF+deg/LpVON/9NLp8x24UfQdfoKd"
			+ "LeiOJEbDMvI9MY4osLU+Z51yd7Fc+wz2ApFF4bS8Wfv556HtUsoxkxYDqMj0PtVW9iSRo1HyMxDBh2xTZJ1VGglZRIuQM8ZyetAhJbjyQ05G4PtG0delVWSf"
			+ "zEeXESrjIHOenFMW4e42lPlMR/XbinS3G9vJhGGUN5gbnGAOv9KaAT7R5155MQJVeST29+KpwTQwXMgRzIoU7ff2xS28zoXeIZZ359do7e2aqmMrdsrjaOeP"
			+ "SmSVQnmMzSICdx9qd5Cf88x+Z/wqzDIQGwqnJ/i+gqbzW/uR1rcg/9HMkSZ4f7QuTuLnH4Crn22Aws5Db3QgY9/8BVEMfs5tieASRTLX90vmtzhSoH+fSuA7"
			+ "E7aF2ORpCgnIVFAUewH+eK1nEq3KeSd4xyp9qxZZFe3SJeCOB9R0qaBXslDXBOXGV56CpL8jYWZHvBHF8o6sPcVHaXURkeCQjk8dqz4nczNKo25XlvX6UxFt"
			+ "zZzMvXgjPtSA0NsTS7ZFx/d5wP0q7BGIj5avkZ4HQDiucE0ssSKT9wcYFWAHijVsYJYNn6joPYUth3N6W7lTcGC8ccfpSJvbyo5OuMkVXmkhEsETfw8n0xiq"
			+ "RZ57zen3CoHWncLHQrcbrgxR/wAK81FfEtCU7nAFU4pF+2KBwpGKlvZvLQkdvu+hp82hPLZk9s+4ebnCrx+XFSctdZ/uDj8azrbcbaKFsYP3h7Vb8wQIzn1x"
			+ "SuOxfaUKQvcnFSVkW7Fp2z/Dj+VaKv0B71akZuNiaioUfOfrT807isSZoqPdRuouKxLRUW8U4MKdwsSUtM3CgNRzE2JKUU0U6quIcAKdhaaBTwtUiAwKMUuD"
			+ "S1VhDcUYp1JQAzFMJAp5qpcSbEz7is5SsXFXJs/Pt9qimIAH1FQNNi4Ueo6VHNJuMmB93HNZOorGqgWPMO9x2XFVnAE0b/XFVoZyLiRT7H9KdHMJZR8v3Dz9"
			+ "cVHPc05LFsuPMxnDLj8jVaA7JZRjA3f0qIyb5pJFHIUCofN808cL5nJ+gpcw1ARg/lPEAPmJ2+g5pbCPzICT95yTuBx04BFVLp5WkW2U8SE5P+z/AJ4rStX2"
			+ "AwwqPl9aExtaFe2upJfNtpxtkXjj+dU2I2h5MbiwH4Ci6KrKZlO2SP07+1ZcMnnxmWU5IJwCOP0o31BaaF6MI5Z2A2xbsfXqOPpWjaybljiQBNwyT6fSsVld"
			+ "bT5D1PI+lJHO0YDsc7eFU9KduwGrfM0o8y1PMZxuNY89y0luk02HOSDnsO1OM9zDblpjlHPbt+FQTeU1uFVj0I6fjVxIewtlceVdjzDiNs/TpxWhdYMszR/x"
			+ "AKPbgZrNHlPGGYc7NuBUCpNyZJO3rVcpKdjbtJYYrd14MgDAAde1Z80pmb7SRgsCxHoPSoEOHBTDcAYHfPWnzbWicpx6Adqm1hp6DIltSgMvX6GpNlh/lTVJ"
			+ "B8vUCnbf9pauxNz/0shmVZMkdRTYzvxCuBvPU1NFslTYePmGPbiqc5MMmwdRwK4banUWfLMS5f8ADml88zoNwJ28fh7VSjLCVml6nvSmQIqqnJ/lT5Rcxs+b"
			+ "FDHmMYyMGoIohCyzOcr6diKZBFmE+YeR0x0qiZZOST04FQo9i3IueZ5cnyLjuAOgq1Jeo67SfoKoo5ZOeuP8inHypnDr8oXtRygpF44nAkc+iqR6VLdyNFMI"
			+ "kHT07VThcspUDbzxj2qcTHafM6t0zWbNEyxNlDEwbaM5Gf5VakmFyot5flZSc/hWNv8A3imfovIFPlO+Xd0YjjH60W6Bc09PIlZx/AB8p+lJdXBuAgQcbv61"
			+ "QiuDHEUT+EjNPc7nVkG0cYFTsNG1CixhpHbHcj6U+3bcqzseCpxWXgKhaRmy4wAPSpZJxI6xoNqoOcUrjsacDbgPcZq8cKKybe4idvMByfu4HtV+RhtwKpS0"
			+ "JktSdRkU7bTInGBVgEVojJ6DAlLtp+aXNOxFykl5bPObYNh1OMHj8quha427XE8g7hia1bPWYzGEueGHBI/Sn0LlHsb4WnBRVFb+0JwJBSvqFpECWkHA6Cnd"
			+ "GfKy+AKeK5Oa/nugdpMadgP611MWfLXPXAq4S1sKUGldktLSClrpRiJSGlqvLKEFZ1JJIpK458DrVO7CiM+mKa8vHXiqz3H7rcfyrinUWx0QpsTAMqSDqoxj"
			+ "600yBFkLnHv2qhcTEOssbde30pTIkccnVjIOfT8Kxub8oy8kMJSVf4hirdu6iTy2AXPK+4/+tWQ8wktFQ4ypx/kU57glYXQfOgK/SqSBlm+uXgl/0df94+ma"
			+ "py3YhnHk4fzBz7flR5jG3MRIOfzqhCgRlkI5qku4m+xfSP8A05nkbHB5p0EpM77X2pxx3I9Aao3Ks581G7UxpyqjeOcfdpqN9gvYsvkys8nPOM1VUxRvIkY4"
			+ "B4FRNMFRQOUzTI1y29TWijoZuQ9fPkXdGfbFP8gHavU9/rUc0zRgx2xO3HNNcfIJd2D7VQixFPFsMN0OTnPH4CqQVkOB93p+VWMpdcNn1/GoVm2bQfug520k"
			+ "rbAyeaMxrg/jUMY3x4bjsKiMhdg0n1ojYPKWzx3Ht7U7OxNyNwQQ44NTxykxc9elLc/NjbwOOlVUODtNUtUTsP2ggUbB/k1DIzZGT2FR7j607Bc//9PnJRJ5"
			+ "y44Jqw8Tf69uRUbxeYodSPk4P4VH5rRny+x4P0rkRuNXYZeDxTkQSyEDpR5KvlIccGq5kKAKnsaLdhGxHE/2b5WDbODt64+lUHYMw9Kn81lAaM7Tw1I6L8tx"
			+ "jgnH0qUUx0aukgI6Yz9arLxKJPTtVmOVVkXYc9qjiBkZuMn0oVwLYkXG9jgYwMVEX3SYk7DIqGMsYyB29KsrsKgyISR0pWKuSswuIQv93pSxuHhJXqnH4VUu"
			+ "Xff5SjAFTxK6L8oHAqLaFX1EhJGEboTk1bP7vntUOxZLUSAgFD+NOGxoMs33TipepS0J15HmrzipmYLEWbvxVTzMuCOI88e9TMVcNGwwo9KyaNEy3ZnLjACc"
			+ "VpB0aR3OMKKxMkRjy/lAqZCAOnXqaQGp9oUQBh64q3HJlSfSuf3E4jHbmpTcOsRUd6E7DcUdGr9BUtYCXn3c1NcX3l2byr16D8a1hO+hlKnYxNRkRr2THIBx"
			+ "x61nNl8EcchePfpUJkJbk8DvjNWGEqBWY5TI5A468dK6kraGdy/f2XkKsi5+Ybce4rLRmIXd09q6O+3/AGOJj/Cck+mBWDGrbQu3gf8A6/pTkgizZsAJJki6"
			+ "g/0rsVNcHYTLHcJJ/d4/+tXahj61jsx1FexcBozVbdjrVeSfHSrdXlRiqdyzLLgcelZ8kmQSe1RPNuFVJJAFrjnU5jqhSsOkkzgjtVeSfMQB7GovMXqe1Qyu"
			+ "m78KixqQsS7ZWpTMUi8kdMcVVJwxB+Wmj96uD37+la2JuOSMOpkJxtprDcgbOBUDtj90GyKSTEifu+NvaqSIbHg+W528jFRESBCF/i/lREPn8oHk9KvCJYQ0"
			+ "s/3cdBVrR2IKkRwFyMAg/pTFbznLMMf4UCUkkRfJkdepFQK7ruK9SKqwriSDzW+QEDpUyQtuVXOPSoXk/drt6nr+FCSvES2ecYos7aE6FqRIBEyIQHB/H6VX"
			+ "V9gwAOKrs3mZPQ1My/KuzjjmqtYV+w6SWQ8p2+6KhlXC7iMHFN+beEHYZxUqP53Ldh/KnsBFEC5CjoaGHlnEPOD1pM+XwO/pTAxKdMCmSThwz4NTpZmQ7iQF"
			+ "xUMCb5W8w4jQbmb0H+elLeStJwvEY+6B0otYYrJZqcYL++cU3bZ/88z/AN9VXMi9AM4pPMH9ynqGh//UwreSPfuZAR3q15FrIm6MEZ5rGjYhsjtVq3lMbFQf"
			+ "lPaua1jZMjcNA5z0xxUihJINpAz2NPucPHx26fSqqZ2Y9eBR6CHeYfLCnoDgCp47hRAUIyuapswKAgY7H8KtqsUsaqo2k9fek0NDS7kblAH0FMMjq+7OKWOK"
			+ "RzsBwfyqSS0mjwcbl9qAJoJPMBD8DtUci4/1XPHammKd04Xp6elRg7Vye3SpsMv+bsCNKu7IqWRNigwZCNyN3UVRMu9FV+aebl/M2MAegqLF3RPbSbYyh9c1"
			+ "E3GRj5G5wKtyQCMeeuNvQj3qr5sS85HHaku6H5FlEjaIvGcY7elLFKSxUdx34qEMY+UjxnjOcihVjwrDOaTiUmWDmL5XPXmrActFkDG7pVWSWGWQHGeMYqdG"
			+ "WIrBJ930PGKzaKRPCyrxxn1phky3NQfIznZnbSkSMfLHAAqbFXLTc4xTNUylnEnqc0KeBngZxWjqNqJreL2FVSj7wpPQ5u3iSY+WvC/rXR2tvBDF5bANn1/S"
			+ "qMenmLlG4+lNlWReuce1dy0Ofc0oZ0vg1rcRfKvB57jpisrUbVlkPJ2dh7U2IrG2Yi2TU8/nypnbn2obuNIy0OzEifd6H1rsvNYRRsD1UVyMdrIXGAcV1Vwp"
			+ "hs0yelctVdjWPQcZie9RM/NZiz1IZa5GmbKxYeTAwKqsc8ZxTC5C7iarklhuJ4qlELkpkUr8gqF3wdo60nmxpHgfezTFYOpZuMCrUSbjifMXBGPU1XB+by4v"
			+ "wqLc+MJzngUhURDL8N6elaqJm2Sq8cQJYZcdBUCB7g4H1z0Aok8raABgmrSMisLdem3LfWq2RIx/Lhx5fU8VDJdSKAg7VOYUQNKvTtWeCXbJNELCZMh81CVH"
			+ "TqP8KiYHACnmnhxCfugn0oikjTMrct2HYVZJIIYEh/en5vQVUmkVeigUBSSTn3/Cqx547VaRLJzzGZBU0ZO0EjgkVWjwsZRxSmU5CjoKGugkW5+FLR4A4B9a"
			+ "pxOwJTsQasQRmeU7s7atyPFYEC3UBz1Lc4FCVlYDMCuBtI+YcYq4sEMSb7hjg/wjiqf2h9xfOWNPdeQzde9MCzcyYTyEAC5yfc9s1XjImXym4I6UyUsOBVYM"
			+ "RyOtCWgrk20oSDRSlievFGaeotD/1eVHzAuOmKhD4ZWp5jKwiSP7rZH0PpUW3gZ49qxsaGyEDxt9M1mnJiwvX735Vet59iZPpUPm28rAyR7c9cGsoaXKdiBs"
			+ "MMgdeSKVxhI8danuYVji8yDpVWSX5s+nAqxbFmYv0U/hRbvNAfOTkYwR2qvE+DvbrRFLslLHvwaLAaRRm2XEXXqQKinxM4fOARxSWUyoTE/RuntSM0Rl8pyQ"
			+ "nTIxxmpsX0K7Oq/Jjn+VWHBDbmPB5BHQ1AYlSbazewbtSujwjypD9PTHtRZCNPzFubNif+WZGaoCIkbwOKkgQrGwTlJVx9CO1EAw/wC8+7WaXLexW9h6XDp8"
			+ "pPXilMkiLjPGelRlRJIZFPvwOlSymNgMAUDRKViJSSE49j0zT3nV3UTLz0rPAKnaeBVuN/MlG4DmpcSkyz5jWsu3blD2p+8luBj/AAqr5ksbEP8AdNBLMQx5"
			+ "7D6VFi0y6XCqPL5x+Van2jzIok9Qf0rnuWAUda0Jw1tBGf4l/r2qqejQSV0aShhxSuu9cYqKyuROn0q8VyOK7LHOUVgCqWA5qyj8VIqcYpCNn0osFxE+9mrV"
			+ "0fMtMCueuLzMmyLjFa6XAiii3nh+tc9V20NYIwZVMZ4qHzSOtaV/AY2yvQ9KxHJrBI0uWtxk57Ugn2ngdKrK3anZXGT+FPlFcdlzkqOKQo7R7hULMxGBSO8h"
			+ "QKDxVpE3JA7xx5Tj3pGmO0ADPuagO7AU9KdLKZMRgcLVJE3CRyVUt1qa3RXd99VShaRcDp2qWNjvd16HihrTQRcmkURiILvPXHoKzmV4m3EU8zCL5Yj14Jpn"
			+ "mAr8/NEY2QmxNjSnd09SeAKumO1iQKf3hPXsBWecOMKfpmmYdh8vatLEltpUhOwR/L0qiVDPxwPSpHnLfL/dqaGNJWErcKOtPYRFtBiPc1EYpGIVVPOBxV6V"
			+ "y7fu1ESDoO/40kbJuCh8kUJhYuR5txj+I+lMjtoYwWuPm3eoyf8A61WEZBkqPz6n/wCtWdNKxJ3ZPH0FCAsyXNs6iBYwAvQfT6VTm2FvlGPpVZUTG5uBnAp7"
			+ "SqflHWhoLj5eWz7VWKd/apGbZhD6A/hTGORxQtCWAY44FG8+lN37AFAHAo84+g/KqA//1uSjldYfJHc04INuDiomyikj2pgbCKKxsWXURlhYDov9ai2lVBHf"
			+ "ip4JWzIn/TMn8qrn52byzg4wBUpalFqxb5ZI247gfpVCUYOB2NPjYh1c9utNB8xixIH1quodAxlQB1pclPkFSqnI5HtUa5RzvwaQiSPftqWYqJz5Y5OMUkQQ"
			+ "zKY/ugjIpLlsXLhPp+VT1K6FuNovO2yD5ZF5HoaZO0ZVY2HMfA+hqjuI5IzxgU5CDnfRYdy5alTkBsH0PT86ZErRT4ziqxdVU4FOBYoCOopWHcn81opyyDHt"
			+ "UrSpIQrDGOMiq6NHsIccnpVt0iRAJOPcfSpZSGrJmPyJenY/Sm7TG4IOMU4kZVZAMYGCPShxuGB07VIyaaZZE+XI6ZqNXOzB/Cmcjv7UDstTZbFGhp8YeXc3"
			+ "ReTSTz+Yju397NXNi21kccNIOfpXPrMDlW6elVTjfUcnbQvW08kUmY+ncV08M29c1xiNtG5MZrTsrpzujJ+lbp2MWjpRJWfe3ghGzHX8qha42xs/pWG1w85+"
			+ "b5v5U2xJEokDHjvVu9m/cRqP4ePyrLH7n734elNuJt/yjpxisuU1UrI6y3kF3Z4PLKKw5wAcFat6S+0ZHBq7qFuv+tjHWudqzsa9DnCPSmbgD0q0Rng1WdBm"
			+ "rTIaG7xgCkMpAAA4FNI5xQT8uD26VdiBGZmO40qo2C2MYpUKhSe4pMNs3yHimIeP3Q5xlqheQ4wvShnXgKO2KAihPMkPTgAd6aQiIAs+B3qSVDwD26AUJMys"
			+ "WHUjHFMz5Zy3JPNUSAwrbMdqhJI5FP3c5HSrlnapKTJcfLCBy3Tn0FPYRXghMv7zGQOuKle3uSuVGFHQZ5q5JeRR4SzTagHGayHlmYkFicn1oQaIkCuqEMKf"
			+ "bf6xmHYAVCh+Xa3arUS4i3DueKT0EiV2lcbIztGPmPtVMTE/dPFLM7BPLXoTn8qpqapLQTJ33NjP8PpTWBEoOMZ/wqQfN8vpwaTc6H5enpQgHXJQzDb2VRUf"
			+ "tVjCtlj2OKjKAdKVwISOeaTApWGTTdtUI//X4rJ8oD1P8qTBbG3pV1Zohj5R+Aq6BEY8xjK449qxuaWKERCTBj0I2n6Gq6qcjb1H9KfMu05HY0kjAL8vFAEj"
			+ "spVmxjPHFP8Asx8sOnzAjIqPbmDPfIz+IqS13LlCflI3CgZBu4/CnRjdwAPxpHX5iB0pA5AwlHoIngkET9OM0tzlJmOcgnIxUAbCFulTHLqCR2qbaldAeRDj"
			+ "g1MsaSfKowQPzqsE55NWQm2MTRvymOKTGhiQMQRjkUQsUOW5FSebISHXqewprZlYFF4I7Uh2Hz7ZAJkHXqKXcZEAPbirdtp92x5AA7ZrQTRG4y/5LUlpGIvP"
			+ "DdqkXvXQpoIPR2/IVZXQWXoc/hUPyKVkcpsYmrEcY3DPWujk0aZFygBrKlt3t3BkUqB6iobe1ilboO1GQY2jsMVyUm7P14roLwMZWB+orGkHPPWumnojKpuS"
			+ "xyReV5eNuKsQEpIjZyM1UVoCh8zr2pF8oHCPt/lVkG7cjMe09KywFyC/yr6Vbkm3RBge2KoiOD/lo2fxpDC6NuUCxD5vaqal8hT2q6zwRgpDzj0H9agjTIGO"
			+ "tPZAbNixxgcV0KuktmQDwtc5Gp27ErWsflSVD/drmqI3i+hkyKAaZgGtD7O0zbYlLH2FXodCuzywC/Wpt2BtGD5QPaongYDpXax6F/fb8hU0ujxBev8AIU0p"
			+ "9ieaB5/sPC0x+XA7DiuvfRoCfvkfQr/hVKTQ2/5ZSDp3H+FWhO3Q5vYWf5e1NdeOo+laFxYXVsh3Lnnt6VnEHPParRDQvCqMdagJ9aXBPFORFLAHgVSJADYM"
			+ "d6dJIzbY16L/ADqTy/m3EgD0/wDrVHuj3jaKBEZJUZ9KYWBPAxUssmRsAximwx7jufG1etUhEuxETcf4+g9qmDbbQP8AX/AVUaUNIW61Ykz9nhjPAC5P41Ml"
			+ "sNFXdyM+lREFcGrKi34MpbjsKWQ27D5Fwe1UiSuzlfu8c1Lu3qQOoqF0fJOKUL94+mOlOyELM5LeX2U0oYgj0xULj5yfepOn5U7ATDDc5ApcL6iq6jIp22ps"
			+ "B//Q4twVT5eg4q1aSMj7T0YdPeofuJg1F94jnHpWRoaMih/lYfSsyTdu5rQM24AnsKpkeYTSiDAN8oFWIY0k2quQcH86iWFthePkDg04tjb5fAo9BoJUZFJH"
			+ "TjNEG3PPB7UhYgZ7NxTPLIcDr3FHQB0uCxwMU4giNW7Z/KlYIRkHmnRLhxE2eeMYpANVi2cdcVahhEkW4/u/Rj90/Qf4VPFZiHbLJhc9+34Dv/KrxWOPEs2U"
			+ "yOB/y0Yf+yijQpFeGGFMZUtjpu4/IDmtSMPGPlVYh78fpVFboKpMfyfTr+dR73PPrSsM0/tLA/eH5VdiuhjJf/x0ViRIG+9WpDbwEVlKVjWMTRS8Q91/FMfy"
			+ "rQhnDfdOP90/0NZBjtwBsqxDjgCsfaNFezVjaaZl44PseP8A61ZN5elPlwEzxhhj8j0psssij5fy7flVX7WmDG+FHcHlfy7Vqp825n7PlMG4Z2l3cHjHTGKp"
			+ "yW+75krVubWL/lh+7PZTyh/3T2/zxWaC0UhVhhsfdP8AnpWqWmhLZQMbRNt25HpVixTfJl1G36VPJho/NHY4I9KWP90w3VXQRXmXbdfZiOCRj6VZliiHGwbh"
			+ "29qbOpOowvjgjP5VJKxLEA0MaM7JlGxU2A+lWoYGJwoqa3h3SbE/h4rT2i3C4G7JxxSAqLbTR/OelXrQuuSy5Rv1+gpk0qpgy8k/dQdfwFQGaR+JSQP7iHn/"
			+ "AIEw/kKmUdCoyOph1CBMRKoU/wBxBlvxxwKnbUDnYuFPp95vyHArmUdIk2jp/wA84/lH4nvUyNcOhVcRr6LxWXtLbD9kmb4nJP7zI/3iB+gqR5IwvGPyrHto"
			+ "kXhm5q5I0W3bnIrP2jK9miCS5wcA/wAqga7XHDc/QUyQRyfdANVpII1A3H8BVxY3FFkXMh+7g+3SqUwtJ/luY/Lb1HFN83Z8oGQPWonkYqf5dq2Rm0UZ9JlU"
			+ "eZAfMX8Af8Kz9mJRCoyw6/X0/CtSOcxnNudh/uHoauKbe9yCBFPtK5/wpkHNMCWIB6Dk1XAIq3NA9sxhkHP+FU8+tWiSzIobae+OlMkl2oEjGBTAT8uKfsMk"
			+ "gVOAvGaS0EIm2M5bkj8qWSUyvu/HFO2Qo2wsWzxxSt5CNsTmgCAgFAaQKGTK9qc6BeAenamB9pCL0qvQRKh3g8YxUDDZx0BqaNDJIVHAHWtApHEN2Oe1LYCg"
			+ "LaVpem0HvUzQqp24P+fSrQl+QyMcKKzZZt0hcDr6+1G4bAcKcYxTcigMMZIFGV9BTEf/0eRQp5Wxxg9jUZjON3YelWYHEm7djpwPpU6CMxn3xisb2NLFNRmI"
			+ "sPvDjFROrLjb+YqVv3eQOPmxSQNv3I/pwfQ00MnDtuVk4LDB+oqFQJJPLJ2/yoVvmGTtIHHpTpozGVlXowpIZWcGpSHXBx0pm0n5lP1p6Pn932NMQF2chuPw"
			+ "FbsSR2yG5nXdI44Ht71R0208x/Ok+7H/AD/+sKuZ8+UzP9xBwPaoZSDe0Z8+b5pWHyg9B9R/IVQeYu29yWY9SallZ9uT1PNMES7N1F7BYYrk9KsRqxI281Cq"
			+ "BeOxrTtVIGR3HNQykTQ27g/Ma34LbcF4NYLagIm2QAZ/vEfyFNN1cO2JJG6evFQ2kWr9DsEsYv7p/OriWkIGduK4SO5lQ7kc/ma04dXuI+C2cfjUqceqBwl0"
			+ "Zuy2cb8I2D6GsaazmX5WXcv8qtx6zGwxcLj3X/CrgMcy+bbtu+nX8qpW6C95aM5Zx5OVHK91NVpESRcqMqOx6j6V0lxBBcr/AHXHft/9audmt5bd/T+VXe2w"
			+ "WuUYYFEqhm+TOTXV/YrOQfcBrAZQw+YbSO/anQXM9tx1A9f8/wD1q1TTMmmjaezt/PiwMBUZQPbiojpFuTlGYGs8avmYJIhTA71fF8rrwcL3P+FMDDkMunzS"
			+ "IATz17UG6d/mAwx6nHT8K1GSW5AAGI+3vSPbwQAZG5u/oPas3JIuKbM5UJG48A9T3P8An0qVQFGF4H60krs7ew4AHQClQfMFPLf3RWb1NIq2xegTeBtFa8en"
			+ "Mw3SfKPem2kcgHGFHfH+NTPf2cPAPmMP7vP69KxS5tynJrSJdgsrcdCT9OlOlsYyOAf0rGk1ifP7tQo/OqcuqXLdWOPrV+4l8JKjPe5pPpqk5Gcfl/KqFzp5"
			+ "X/VtWab27B+WZh9DU0erTgbLkCRffAP6VUWhO5nzebE22Sq/mkVrT+W6eZGdyH9Ky2XaxU1ZJDvUmpgc4DcHsaqMmDxUqcrg9qtEl6TF7F5cv+sQcH1x/hWB"
			+ "JGyk5rcGQolX76YzRcWu+I3EY4Az/wABPB/I/pSvYVjAIIAqX5hGSO1OkTHGM8U1FOd3THrVkhs27AeOKiGN54+lTtLuxt7dsVGCC+9+McUIBpO78KZ16VMy"
			+ "7V9KWErGCR16UxWL6NFbgA/ebsKrXMwYhV5P9KrsSW3n6VHGcMT7UrDHOzMixr0WkQJjLfgKnQoiEsM89PYVVPzHNUSBzmkpxpKAP//S4tSF2nH5VYgk2Exn"
			+ "7rDj8KhlOQJE6f1pFJ25IzjpWRoTSjKkd+CP5VErNGcIKuFMwiVOdv8ALFVSm7nOABk0osdhzRll8xBwew7VEjFsK3TpU4EijH/6qcIUYBh8uKLjsIF8txjn"
			+ "ilG3I4wKljTPXqOBUoi3lBjAPFZ3HY0P9TbGMcADJ+p5/QYFRyI0duq4+/irDr5kUjeu79Dj+QpbsfPt7Ljj8KWxaRkupeTjtTwjKORxV4IOCoFMlTGV6elS"
			+ "2PlIgoOAO9WpsogiXrjLf4VWjI81Segq3INyE92poRnhSSBnB/SnsCpw3XtioTJgYk5IpyueABwOBSsO4rOQ23ocU8FWGM4OOaYzg4Dg4pyrb4+Q8dqFEZOA"
			+ "E+YnPcCpIrgo29CR6dsVXRNvEWKVY5jww4qrIdzbW/MgxccMP4x/UVJkHrjn/vk1jJC4I44qzFJJFk9V7qRxSsg9CzJbb+Iuf9n0+ntUBiMa5X5tvUelakJi"
			+ "MfnRZDDse30PpWfcXvmSHygPQsPuitIqyMpS7DEaFgYWiBz6cHPbH+FXbO0hB6bmXr/dX61URhGo/h3D8T/gKsQCdgN/ywr/AJ/GnfsRymg4byWeP5jnBbpx"
			+ "7DsKqGE3WWQBUA/AGughWN4Nq/LH3/wphgjGFGESolDqXGpbQ5ZrNhhE79SP5CjfBa/JHhm9M8D6nv8AQVcv7hTmK3+VehPc/wCArHAdRgYx2qLGqJnuriQY"
			+ "c/L6DgflUBl7ClPmN91QKhZLjqMUJIoV5XAqI7mGWpBvUjdUvmfL93NVYRTMpzjHSn7t3XrTv3h6qMdsUYi6Hg4xUtEliCXyxz93oR7VHdRGJyKEAEY461Pc"
			+ "SB7eP+8qhT9RVdBGdyRiiNfmpDw2KniXHzUE2JY+X2Hp0q/ZMUiYNyEbDD/Zb5T/AI1ngnzMAdj+grXWIGS6j9Qf1AIouOxzki+W7RN/CSPy4qs+Sdi/Tird"
			+ "z+8mdwcbgG/QVW+YLxxVIzImB6J+NQj5jhugqztZuKYylSVA+lWmKw2RznHtUOe1Sshzk9hUotvLBeY44wMetNCIkXzFyf4eaiTO/HQ1aEoMZG3AVf1qBTg8"
			+ "d6AEkbkp2FMxtGe1KVLHf2pWGQO1MQnXvRj3/SmN146U3Jp2A//T45N0JINWlSOSLMfB67f5/hUwi3ybHAHv6UpjMfyZ+nuK5nI3USCOJzkLzt7CmCVVyr9D"
			+ "xip44/3nl9M8Zp7QNzg784xjii6HYiG0IV61EPMUE44HSpfLzLjbnt6UqiQExYPSgREvnHlePQ1YBYbSc5PJpyxiRNy8c8+34Vc8lcJ0yv61DkilEtKmbb6E"
			+ "1YlVWTI69/p2q1aQZszL12nn+v6U6GNZmAT6flUt6GsbGZ5LImcZHY9qrS4IA/St+53R/uWHQVkvA393IxU023oxzS6FSNcuEA68YrTNtLIB8v3hwB0+WocM"
			+ "MIqYwOD9K2beVkbccEHBPsfUVpbsZoyW0x2hNyi7vUf5/lWebbjJGfp+lehJEG+dOD3qtdafBKPnXn1X/ClyvcSktjgwIo+CCKaVjJ+Uiti4sY0bapOPdDVH"
			+ "yFQ/L0+lNMshjQL8uKsKxBwDjPAFQLw+2MlvYcn8hWhHDcDG/wDd+2Nzf98imFyusU4BaU7V9TxUj+VCMnOT27n6Dt9TUjkq2c7SO5wz/wDxK/hWeZEQnYMn"
			+ "uev5mlbuK44iWbIYhVPb6etMZlV/Li+b0OOB+FM3s5wBViG3kMgjjALHtTvYXKX7a080DdknPLHtWzHFJEwSU5A/hFURcRwx7FAJjwoyePc5qJZ57tikGdo+"
			+ "8/p/hVUzOoasl6kLFRgsP4R0WmfaBL0cFjwQ/wB1vYHtUUmnCGMGE7h6+tY0oYE7fl9q0kRCJoy23YKT/sn7w+nZhWeI+6HIHbHSnw3zoPLk+ZfQ/wBD2q6f"
			+ "s93gg/MP73yt+DdD9DWNux0J2KGM/WozFu96uyW0yfKBu9m+Vvw/hP4GoAqKds26M+//ANf+lTsXdFEwMPYU9IGPUitRbEsMgjH0/wAKtRaYuc7gPYCk5dg0"
			+ "Mb7MRwMVLDprzAyvgIvU/wBBXVpp0O0Hbn68D8qmNuuP3mMDt2FNRkQ6kehxj20kgB2kJ0ziqc43ZA4H6Cuqvpt8ZEPCDj6/SufeNnBJwM80IDJb5H2jtUgB"
			+ "B+lKYscbaupEWkXd3ptgoleDIm3D6D8eKvG4AmlI7/04psqiN8r0UZz/ACrOGfKdz3wBTSJemhSYtnpgYA3fSox8xBHQfp+FXfKT+MDiofI+bjj6VV0RYY43"
			+ "E1GuUHI/Op8MoOeMnofajACYIGV/Gi4WI44U2mST7oprjzJPm6dad87KSv5U0L3ancViALuJAztpjEqfwqcFenammMMMgY/z2qkTYgOfKGOhNM+8MD0qfyTt"
			+ "AJ56ewpihQCvTPA/CqERlkHGKTcnpThC7c4xS+Q3p/KnoB//1MScM3+r4Y4zj0o2HcW9OKfM6pIQBk9Py9Kckkfkn16VwX0OuyuRW9vl/m9vw7VOEEb7MZ2n"
			+ "ORTo3XHWlbfInHXsPSpbdyklYZIgUo4xt/UU1ZlU71FPIbAZPy+lR+Usidxnj6015gSxbAhbgKfT+VODRH5FPPAqqP3aCM9s8dqZlQQygDHf2o5RXOq0e6Uz"
			+ "GB+EkGAPcVcFm1tKyR+oZa5VJtoyvykNn/8AVXa2V0t/CM8Sx9R/ntWtN/ZIlpqSbFuQsyjkcEelQy2ydxVvPlt5iDB6EVLujkXI49vStbIi7OcNoCwIPSpk"
			+ "jCsWHU/56VpPBgbhVUoAfShRXQdxI2kgOYjx6Hp+FStf4/1iEfT/AOtTNuKY5TGFPPpSdrDSIJb2E8HzPwqnuss5MTN/vEVbW3GSzjBqI20YO/H+FYOSRsol"
			+ "ZrxIwUiiCj6/0GKpvdtjbkKD2UYqWeONWIBBH0qAQQsMct9KFIfLYrllbgng1VYzN8ka7FFXVgjDZP5VacZXkBFHQVZDKEMcr/eOMd/arvmKg8i1HXrULHKg"
			+ "n5EPQ+v+6O/8qb5UjrgrtT+5nk/7x/p0o5V1FdvREbEP/qyCB1bt/wAB/wAa1LC8NkNvBiPVf8KzXEHTAB9DQvlqApXAxx2FO/YFBdTs4ZIrhPOtDnHVfSqF"
			+ "zBHcdBtYVkwSi3PmQvhh0xWqt1Fd4z8kn5A/T0PtTvcnl5TEe2eM9OB2ojI3bcY/lW9wflmXp36EfUVE2n5+ZOV9VqLFpopJPNF8itx/dPI/KpVvMfKVH/Ae"
			+ "B+RyKGtJIQNwJHZhz/KqkkKgb8kUK5VkaUU0WNyw4+gx/wCg1fiuox/CR+dZlmQBtGcfyrVCAVaiiGWRecfIDVeaV3GWpSGPAqLY59qdibJGQ7SzNtHA7AUx"
			+ "kchUxjHAJ4qwbSYNkfnUDI6fI/AFZNWNlboMMcJOWYOV7CrMVs0Cm4lB5H5CpYfLXaQm4j8hWnNm5/1vyxD+H1+tOnG5E5WOTuw8hAQcN096huYGhCRAbjjJ"
			+ "A/SuluBBag3cwAIG1F9B2rkppTJIZS+C3X/PpVPTREIeI/lGeOO9RPJEPkBw3b2o+VsbvmUd8UzyUEReJVyeoPP8u1QkivQXzNx9h2qPCsQEOB3zx+gqbaxH"
			+ "zDaR61Eq9TtP1oFYc5WLiMe36Um9NhUDn0pMDAEZyRxgD8qmKRbQ2dx6cdKL2CxRWPd/D6D/AAqQjHGcD2q6hbiOPA+Xr2Ge/wBagaEKQFbd79AMf4U+YXKQ"
			+ "OiAMpPPFQuFJBbtVnYD07nvUeI81SZLRXY4Pc/Sm7vY1oRmJRjP5Cn74vX9KfMKx/9XBab1UFvp0qNQRMCw+Q/y9alQxklJOc0ZEanYOK4l2OoI3w27jb2+l"
			+ "PEkSjAI45zUB2+WQOtQiAuoYZ7cUcqC7Lu5sHYQCDwp4xURmYJ83rzUO7j5cY6cdB7UvmD0Az+lPlFctCViismN/3Tj2p8kxeMEFRjgjHX0rOdkXnPB6Y6VG"
			+ "xKAdxT5A5zUSQwkEcHHAH+FXLa5mgcTRDBX/AD+VYgbcQSe3GOOKmWT5dsZI/wBk9qlxGpHpFtew3q7T+7lHVT/SnhRt+fg9OK4fzdwEvQ8EjPp6VpW+rSRK"
			+ "ISNyj0HP/wCul7TuPktsdX5ZK5U5+lU5IQeCp/Ooob2zd8RyCM+hqzJ9rIzFtcVas0TqislsgOMGryWyYxzVBft27LKAK04nlx81Csgk3bQY9nFjpWdJYqWG"
			+ "0HFbDu+OKpsZfUflSlFdAhJmfLabRlYgPqf6U1Yljjw4B+vT8AKS7uxCPnZU/wB4gfoOawJtZjXiMGQ+42r+XWqUUDbNcrEuTEBx1Y8Af0FZcj7m+TEh/vEf"
			+ "IPoO/wDKsmbUJpzmTkDoOgH0HSmG7l9SPxp+gJdzSZRku7Eue5/zwKrMwj53nH1qq11I3U1H5hI6A5qbM0uuhejaJ+hP5VZVohwuM+lZysFwR1pA75zn8KVi"
			+ "rmvvCD5himed36j0rME8qe/t2pwuXC7iQPYrn+VHKHMjoLfUimEmG9e3qPof6Vt2xil+a1fn06EfhXB/b36bR7YqZdRkG3HykdxT1RnZdD0dCeki/iP8Ka8d"
			+ "vJxwfY1y1t4ldAFnTzF/I/4VqLq2l3Y+/wCWfRhj9au+hny2L4hjj+UAKO2KeIFfg8j6VSCueYZsj86tRNcL1UH6VNyrFxLZFGKd5C+lKjuRyKa5n6IKtWsZ"
			+ "ah5KD71UbiNJSFbao7HvSSxXrdZFQVmy/wBn2x33U+9vQVLNFoaTpFEnlw/NJ0GO1MSKOxi868bLdlrCl15IxssYiq/3v8BWW9/cTHJ7/wB7r+FHNbZD5L7l"
			+ "q8uzdSl5OB2A7VmYic5C598VIl05AZMcDnIqB2kzhxhepz/9as9TTS2g4/IflHHrSlm3jnAHGBxUfmx4yV5/hzVfepk9PUCiwrltY2H3Rv8AU1IUXbmL73sK"
			+ "rl9gBUDB9OlRrKQTt59B2pWYroth1H7vbk45JqDzi8m08L6dMCmLLI2d+FX2oLKYijY5GAf8aaiK4m9mfahpFlQptbgdqfCPLXk59/SoZDGW+RQFHanYROrR"
			+ "7MDtximTgcAAAe1Mm2gYQYPc/wAqjCSjG/pjvTS6i8iVZTGNq9PpTvtL+/8A3yKgbcxyrbR6U3bJ/wA9KdhH/9blQqyDMZIYdj3qfdtttvfNQsBHzGePSmg7"
			+ "vpXM0b7DxlUDGl87D5UdQBSd+OgqUAY4paCImcRnbjOeaRkX747jpU6whhtb8Kjzs5AH1ppjsJ5DJGHzkPnbx0xSuiuB2xx+FK0m4bew6VTLkDJPWmrsWiNM"
			+ "LEQsWMAdCPQ0yTCMSSD7VWWVvLwBx3oXa2ByKmxVyzHcJgJwB1q3ESTgfhis/wAqPd6VOgNuwlifGDx/k1LiuhaZpM7kYzjHanIkvB3lT2Gdv6CswfvATuAz"
			+ "2HA/KnCJyQQ9CjbYq5tBrkfKZGB9Cauw380fylifTjNYUbMn3sEirQmgTmUZwOgNQ0y0kbT6qx4EhHHoB/SqE8jz8SSyY/3uP0qNLq1x0OPeonuFzhOR9BUp"
			+ "Mq0UZ0kEWcrVUxAdsVfkbHHIPtUA2ggGt47GLRUKx44puAatyKnPaoSFAywq0TYgwBSfQfpVgbT9KNq+tMmxHz/DSlcc5pwQDpSYYHj/AOtQMUD3FGwHpSgH"
			+ "v+lSYX60gI/Lx94Cl2AVP8o6ClwuSO/tSGkMWPpnBp/lx8DHX3xVmFMnG0jjnmlKHds6f4VFzTlGx2ypgplf91v8K0op5oeA78e9UFEkfQn9KlN4w4wPSpd+"
			+ "g0l1NhdRul/iP6UNeXMo4c/hiskXTbfkH6dvaoGvU3jyvk/4DUWkV7vYs3AuHbaSxx6msww7GwcD1zVpriaRcN09uKj2sF3E9exOa0XmS0uhDw38eRUEiqAQ"
			+ "P1oliydwbH4cVBhl54+vWrSM2MZghwTzU0c8hO1MYAqI26HkfpTfIAGVp2RGqJn8x224IJ/Kqw+6CRUwLn5ScU0ptb5vloQmIryAfIOKfk7twP1/wqM5XPl5"
			+ "4pWTco7H0pCuTIYyhHRjQAgTnnFMWPAznPHNQqNp9u1Kw7ltAjDnv+lM+QHC9qjfnheKaYn4PQDvihIdyw+5UEg9cY/CozMzLz+tMJMhJPantx+764osFx6R"
			+ "x7fmNP8ALh9f0qkY5M/L0pPLmp28xX8j/9fkfNXoKbv9KhXBpchTisrF3JwWPtUisw71WBFNLelTyjRoK3cVAwDP1xmmK4VeKduB5pJWHccSqALSLL2I4qEu"
			+ "S2PSnA5PFVYLku8AdKl+QINmKqYY8VKrBF+fp2qbDRKr8gOtWI5YwPr29KqeYrEAVYVI8AsOtJpGkSbCMT/SljSLbjBFM3RKMA0z90w44FIssIiBsFiR9OlS"
			+ "SMFGAM+lUvlHSn+c2KLBcdh2OegqQttGN3HoOKgDntT95xyBTEMDMHzt59zThI27PFR7s9Kd5vH+FVYkk3nOBTC3PNM39PakLUWFceADyKQ4xzTSV7UDI6Ux"
			+ "ACrHFP8AlPQ0zJHapAQeCtADQd3PYUpJ6DpTto64ApgQDmgZMr7T0qQTD+7ioNrcHNPO/oMDFQy0S75c5Tp6CpN8p+Vh+NVwZCcg1E+/d8zYJ96Vh3L6sRgN"
			+ "S9TgKOKzw5xtzUbzsV69KVg50agxt3Diox85Kjt3rK38YWnLM+MYxmjlFzmuTmPBIAFQMij5ieMVnh/mAzkVc8yHH07UWsUpJkf7kcCkH3sAUjsjDKjmogzE"
			+ "5I6VRmyRkOfl/KomBztz9ac0hXoaIlT7zHFFxC4UDJ7cUsaKxBPRaURq3zdageXA2Lx7VO+wEsyHHyc1EY9igd6azuFx0piSHvVJOxLsO5VsMaXdUDybjSGT"
			+ "PA4quUknV/m4q19okxgVlhiDVpm2DK0mrCTJ9wxg8E1H5LM2R+dQjcw3CmFnBxmhIq5bDhBjNL5o9aWJmKDIqTJ9BU6FH//Q4RmJ9qU8qDTe1PH3akYDchqY"
			+ "bajbrQaTGTrjHNRnIoWhu1SMehB+9R904FRp9+pH+9QMUZp+N3DDikTrUp60ikNEKp7U4KRwKkl7Uq0rl2I9vZqdiLutI33qKA2HgoOlOUjHSoOxqVegosO4"
			+ "vSmFhTj0qA00iWPDDGTxRwaZ/DSr0piJOKTJ7UdqXsKAHDpk0pIxSdqYaBjwPQ08detRrS9xQBNjNJt/Kl70H7tSUIFahhjG41KvSoJvvCpKsPCn+GojsIPq"
			+ "KsQ/dqp3ahAyszNk9qTIAp0lQ9q1sYsQyHPFS+ZkZ6Yqv3qT+GnZEokyCMino4Q89ahX7lDfeqbDTLW7A3GgOAMg/hSP/qqg7VCRbJXaP8aastVjSr0quVWI"
			+ "uWRLIvSgLk9MU2pRSKIygZcE4qPaiDBNSnpVaSmhMXKDpTcv2pnpUy9qsgAjjluMUpy/Sp5en4VHF1qQGDI68U4lOo60knWo6LAWFldRhTgUvnSf3qr0tKyL"
			+ "P//Z";
	static final String IMG_TEST_MIME_TYPE = "image/jpeg";

	private final AiMCQuestionService mcQuestionService;
	private final AiImageDescriptionService imageDescriptionService;
	private CloseableModalController cmc;

	public AiFeaturesTestController(UserRequest ureq, WindowControl wControl,
			AiMCQuestionService mcQuestionService, AiImageDescriptionService imageDescriptionService) {
		super(ureq, wControl);
		this.mcQuestionService = mcQuestionService;
		this.imageDescriptionService = imageDescriptionService;
		putInitialPanel(new org.olat.core.gui.components.panel.SimpleStackedPanel("aiTestPanel"));
	}

	public void testMcGenerator(String spiId, String modelName) {
		VelocityContainer vc = createVelocityContainer("ai_test_result");
		vc.contextPut("testType", "mc");
		vc.contextPut("inputText", MC_TEST_INPUT);

		AiMCQuestionsResponse response = mcQuestionService.generateMCQuestionsResponse(null, MC_TEST_INPUT, 1, spiId, modelName);
		if (response.isSuccess() && !response.getQuestions().isEmpty()) {
			MCQuestionData q = response.getQuestions().get(0);
			vc.contextPut("mcData", q);
		} else {
			String error = response.getError() != null ? response.getError() : "No questions generated.";
			vc.contextPut("error", error);
		}

		showModal(vc, "MC Question Generator Test");
	}

	public void testImgDescGenerator(String spiId, String modelName) {
		VelocityContainer vc = createVelocityContainer("ai_test_result");
		vc.contextPut("testType", "imgdesc");
		vc.contextPut("inputImageBase64", IMG_TEST_BASE64);

		AiImageDescriptionResponse response = imageDescriptionService.generateImageDescription(
				null, IMG_TEST_BASE64, IMG_TEST_MIME_TYPE, Locale.ENGLISH, spiId, modelName);
		if (response.isSuccess() && response.getDescription() != null) {
			ImageDescriptionData data = response.getDescription();
			vc.contextPut("imgData", data);
		} else {
			String error = response.getError() != null ? response.getError() : "No description generated.";
			vc.contextPut("error", error);
		}

		showModal(vc, "Image Description Generator Test");
	}

	private void showModal(VelocityContainer vc, String title) {
		cleanUp();
		cmc = new CloseableModalController(getWindowControl(), translate("close"),
				vc, true, title);
		listenTo(cmc);
		cmc.activate();
	}

	private void cleanUp() {
		removeAsListenerAndDispose(cmc);
		cmc = null;
	}

	@Override
	protected void event(UserRequest ureq, Component source, Event event) {
		// nothing
	}

	@Override
	protected void event(UserRequest ureq, Controller source, Event event) {
		if (source == cmc) {
			cleanUp();
		}
		super.event(ureq, source, event);
	}
}
