
-- issue necessary system privileges
CREATE ROLE OLATROLE;
GRANT CONNECT,
	CREATE SESSION, 
	ALTER SESSION,
	CREATE TABLE,
	CREATE VIEW,
	CREATE TYPE,
	CREATE PROCEDURE,
	CREATE TRIGGER,
	CREATE SEQUENCE,
	CREATE SYNONYM,
	CREATE PUBLIC SYNONYM,
	DROP PUBLIC SYNONYM
	  TO OLATROLE;

CREATE USER ${db.name} IDENTIFIED BY ${db.pass}
	TEMPORARY TABLESPACE temp 
		DEFAULT TABLESPACE OLATTBS
			QUOTA UNLIMITED ON OLATTBS;
GRANT OLATROLE TO ${db.user};

